"""init_full_schema_phase2

Revision ID: 9669f730394c
Revises: 58f3a357343b
Create Date: 2026-09-28 15:29:27.946873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9669f730394c'
down_revision: Union[str, Sequence[str], None] = '58f3a357343b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.String(length=100), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_access_logs'))
    )
    op.create_index(op.f('ix_audit_access_logs_target_user_id'), 'audit_access_logs', ['target_user_id'], unique=False)
    op.create_table('information_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PLACE', 'MESSAGE', 'ITINERARY', 'ITINERARY_PROPOSAL', 'EVALUATION_RESULT', 'BOOKING_OFFER', 'TRIP_ALERT', name='sourceentitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('tool_call_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_information_sources'))
    )
    op.create_index('ix_information_sources_entity', 'information_sources', ['entity_type', 'entity_id'], unique=False)
    op.create_table('place_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='SERIAL PK — lookup table'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên phân loại địa điểm'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL-friendly identifier'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả chi tiết phân loại'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Cập nhật gần nhất'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_place_categories_slug'))
    )
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='Config key — chuỗi định danh tham số'),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('config_key', name=op.f('pk_system_configs'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email đăng nhập — unique, lowercase'),
    sa.Column('password', sa.String(length=200), nullable=True, comment='Bcrypt hash của mật khẩu; NULL nếu đăng nhập qua OAuth'),
    sa.Column('full_name', sa.String(length=200), nullable=True, comment='Họ tên đầy đủ'),
    sa.Column('status', sa.Enum('DISABLED', 'BANNED', 'ACTIVE', name='accountstatus'), server_default='ACTIVE', nullable=False, comment='Trạng thái tài khoản'),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'OPERATOR', name='userrole'), server_default='USER', nullable=False, comment='Phân quyền người dùng'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete: NULL = chưa xóa; có giá trị = đã xóa lúc đó (UTC)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('agent_session',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id — chủ sở hữu phiên'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Tiêu đề phiên (người dùng đặt hoặc AI tự generate)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Tóm tắt nội dung phiên do Agent tạo ra'),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='agentsessionstatus'), server_default='ACTIVE', nullable=False, comment='Trạng thái phiên: ACTIVE | ARCHIVED'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_session_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_session'))
    )
    op.create_index(op.f('ix_agent_session_user_id'), 'agent_session', ['user_id'], unique=False)
    op.create_index('ix_agent_session_user_id_status', 'agent_session', ['user_id', 'status'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False, comment='PK = FK → users.id (1-1 relationship)'),
    sa.Column('travel_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Sở thích và phong cách du lịch (JSONB)'),
    sa.Column('special_needs', sa.Text(), nullable=True, comment='Nhu cầu đặc biệt (dị ứng, khuyết tật, ...)'),
    sa.Column('default_budget', sa.Numeric(precision=15, scale=2), nullable=True, comment='Ngân sách mặc định — NUMERIC(15,2), luôn > 0 nếu có'),
    sa.Column('preferred_currency', sa.String(length=3), server_default='VND', nullable=False, comment='Đơn vị tiền tệ mặc định — ISO 4217 (3 ký tự)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_user_profile_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('PLANNER', 'CRITIC', 'BOOKING', name='agenttype'), nullable=False),
    sa.Column('scope', sa.Enum('WORKING', 'TRIP', name='agentmemoryscope'), nullable=False),
    sa.Column('memory_key', sa.String(length=100), nullable=False),
    sa.Column('memory_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Working/trip memory lưu tối đa 7 ngày'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_session.id'], name=op.f('fk_agent_memories_agent_session_id_agent_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_memories'))
    )
    op.create_index(op.f('ix_agent_memories_agent_session_id'), 'agent_memories', ['agent_session_id'], unique=False)
    op.create_index('ix_agent_memories_session_key', 'agent_memories', ['agent_session_id', 'memory_key'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('agent_session_id', sa.UUID(), nullable=False, comment='FK → agent_session.id'),
    sa.Column('role', sa.String(length=10), nullable=False, comment="Vai trò gửi tin: 'user' | 'assistant'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Nội dung tin nhắn'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata bổ sung: file ids, tool hints, ... (JSONB)'),
    sa.Column('agent_run_id', sa.UUID(), nullable=True, comment='FK → agent_runs.id (chỉ có với assistant messages)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False, comment='Thời điểm gửi tin nhắn (UTC)'),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_session.id'], name=op.f('fk_messages_agent_session_id_agent_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_agent_run_id'), 'messages', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_messages_agent_session_id'), 'messages', ['agent_session_id'], unique=False)
    op.create_index('ix_messages_session_created', 'messages', ['agent_session_id', 'created_at'], unique=False)
    op.create_table('operator_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.Enum('PLACE_UPDATE', 'WEATHER_REPORT', 'AI_ISSUE', name='operatorproposaltype'), nullable=False),
    sa.Column('target_place_id', sa.UUID(), nullable=True),
    sa.Column('related_trip_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('proposed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='operatorproposalstatus'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_operator_proposals_operator_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_place_id'], ['places.id'], name=op.f('fk_operator_proposals_target_place_id_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_proposals'))
    )
    op.create_index(op.f('ix_operator_proposals_operator_id'), 'operator_proposals', ['operator_id'], unique=False)
    op.create_table('place_narrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('audio_object_key', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_narrations_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_narrations'))
    )
    op.create_index(op.f('ix_place_narrations_place_id'), 'place_narrations', ['place_id'], unique=False)
    op.create_geospatial_table('trip_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_trip_request_id', sa.UUID(), nullable=True, comment='Liên kết phiên bản yêu cầu trước đó (versioning)'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PLANNING', 'PLANNED', 'CANCELLED', name='triprequeststatus'), server_default='DRAFT', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Phiên bản của yêu cầu (tăng mỗi lần revise)'),
    sa.Column('origin_name', sa.String(length=255), nullable=True),
    sa.Column('origin_location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Tọa độ điểm xuất phát'),
    sa.Column('destination_text', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('companions_count', sa.Integer(), nullable=True),
    sa.Column('companions_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_session.id'], name=op.f('fk_trip_requests_agent_session_id_agent_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_trip_request_id'], ['trip_requests.id'], name=op.f('fk_trip_requests_parent_trip_request_id_trip_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trip_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_requests'))
    )
    op.create_geospatial_index('idx_trip_requests_origin_location', 'trip_requests', ['origin_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_requests_agent_session_id'), 'trip_requests', ['agent_session_id'], unique=False)
    op.create_geospatial_index('ix_trip_requests_origin_location', 'trip_requests', ['origin_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_requests_parent_trip_request_id'), 'trip_requests', ['parent_trip_request_id'], unique=False)
    op.create_index(op.f('ix_trip_requests_user_id'), 'trip_requests', ['user_id'], unique=False)
    op.create_index('ix_trip_requests_user_status', 'trip_requests', ['user_id', 'status'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_request_id', sa.UUID(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trade_offs', sa.Text(), nullable=True),
    sa.Column('luggage_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ranking_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWING', 'SELECTED', name='itinerarystatus'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], name=op.f('fk_itineraries_trip_request_id_trip_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itineraries'))
    )
    op.create_index(op.f('ix_itineraries_trip_request_id'), 'itineraries', ['trip_request_id'], unique=False)
    op.create_index('ix_itineraries_trip_request_status', 'itineraries', ['trip_request_id', 'status'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True, comment='Tin nhắn upload lên bằng tin nhắn nào'),
    sa.Column('object_key', sa.String(length=500), nullable=False, comment='Đường dẫn file trong object storage (MinIO key)'),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Enum('REQUEST_IMAGE', 'REVIEW_PHOTO', 'SUMMARY_PHOTO', name='mediaimage'), nullable=False, comment='Mục đích sử dụng file'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_media_files_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_media_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files'))
    )
    op.create_index(op.f('ix_media_files_message_id'), 'media_files', ['message_id'], unique=False)
    op.create_index(op.f('ix_media_files_user_id'), 'media_files', ['user_id'], unique=False)
    op.create_table('trip_request_selected_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_request_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('selection_status', sa.String(length=20), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_trip_request_selected_places_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], name=op.f('fk_trip_request_selected_places_trip_request_id_trip_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_request_selected_places'))
    )
    op.create_index(op.f('ix_trip_request_selected_places_place_id'), 'trip_request_selected_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_trip_request_selected_places_trip_request_id'), 'trip_request_selected_places', ['trip_request_id'], unique=False)
    op.create_table('booking_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('offer_type', sa.Enum('HOTEL', 'FLIGHT', 'TRANSPORT', 'ACTIVITY', name='bookingoffertype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'STALE', 'UNAVAILABLE', name='bookingofferstatus'), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('provider_offer_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('redirect_url', sa.String(length=1000), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('fk_booking_offers_itinerary_id_itineraries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_offers'))
    )
    op.create_index(op.f('ix_booking_offers_itinerary_id'), 'booking_offers', ['itinerary_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('budget_status', sa.Boolean(), nullable=True),
    sa.Column('opening_hours_status', sa.Boolean(), nullable=True),
    sa.Column('travel_time_status', sa.Boolean(), nullable=True),
    sa.Column('safety_status', sa.Boolean(), nullable=True),
    sa.Column('hard_failures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('fk_evaluation_results_itinerary_id_itineraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results'))
    )
    op.create_index(op.f('ix_evaluation_results_itinerary_id'), 'evaluation_results', ['itinerary_id'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('fk_itinerary_days_itinerary_id_itineraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_days'))
    )
    op.create_index(op.f('ix_itinerary_days_itinerary_id'), 'itinerary_days', ['itinerary_id'], unique=False)
    op.create_table('itinerary_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('base_itinerary_id', sa.UUID(), nullable=True),
    sa.Column('target_version', sa.Integer(), nullable=True),
    sa.Column('proposed_by', sa.String(length=30), nullable=True),
    sa.Column('diff_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='itineraryproposalstatus'), server_default='PENDING', nullable=False),
    sa.Column('user_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('fk_itinerary_proposals_itinerary_id_itineraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_proposals'))
    )
    op.create_index(op.f('ix_itinerary_proposals_itinerary_id'), 'itinerary_proposals', ['itinerary_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_request_id', sa.UUID(), nullable=True),
    sa.Column('finalized_itinerary_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gps_consent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['finalized_itinerary_id'], ['itineraries.id'], name=op.f('fk_trips_finalized_itinerary_id_itineraries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], name=op.f('fk_trips_trip_request_id_trip_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_trip_request_id'), 'trips', ['trip_request_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('trip_request_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('PLANNER', 'CRITIC', 'BOOKING', name='agenttype'), nullable=False),
    sa.Column('trigger_type', sa.Enum('USER', 'AGENT', 'BACKGROUND_JOB', name='agentrun_trigger'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='agentrunstatus'), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Log kỹ thuật lưu tối đa 7 ngày'),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_session.id'], name=op.f('fk_agent_runs_agent_session_id_agent_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_runs_parent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_agent_runs_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], name=op.f('fk_agent_runs_trip_request_id_trip_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_session_status', 'agent_runs', ['agent_session_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_index('ix_agent_runs_workflow', 'agent_runs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workflow_id'), 'agent_runs', ['workflow_id'], unique=False)
    op.create_geospatial_table('gps_location_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('accuracy_meters', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Hạn lưu trữ tối đa 7 ngày'),
    sa.Column('is_expired', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_gps_location_events_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gps_location_events'))
    )
    op.create_geospatial_index('idx_gps_location_events_location', 'gps_location_events', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('ix_gps_location_events_location', 'gps_location_events', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gps_location_events_trip_id'), 'gps_location_events', ['trip_id'], unique=False)
    op.create_index('ix_gps_location_events_trip_recorded', 'gps_location_events', ['trip_id', 'recorded_at'], unique=False)
    op.create_table('itinerary_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], name=op.f('fk_itinerary_activities_itinerary_day_id_itinerary_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_itinerary_activities_place_id_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_activities'))
    )
    op.create_index(op.f('ix_itinerary_activities_itinerary_day_id'), 'itinerary_activities', ['itinerary_day_id'], unique=False)
    op.create_index(op.f('ix_itinerary_activities_place_id'), 'itinerary_activities', ['place_id'], unique=False)
    op.create_table('place_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PRIVATE', 'PENDING', 'PUBLIC', 'REJECTED', 'HIDDEN', name='reviewstatus'), server_default='PRIVATE', nullable=False),
    sa.Column('visit_status', sa.Enum('UNVERIFIED', 'VERIFIED', name='visitverificationstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_reviews_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_place_reviews_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_place_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_reviews'))
    )
    op.create_index(op.f('ix_place_reviews_place_id'), 'place_reviews', ['place_id'], unique=False)
    op.create_index('ix_place_reviews_place_status', 'place_reviews', ['place_id', 'status'], unique=False)
    op.create_index(op.f('ix_place_reviews_user_id'), 'place_reviews', ['user_id'], unique=False)
    op.create_table('trip_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('affected_activity_id', sa.UUID(), nullable=True),
    sa.Column('alternative_proposal_id', sa.UUID(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_alerts_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_alerts'))
    )
    op.create_index(op.f('ix_trip_alerts_trip_id'), 'trip_alerts', ['trip_id'], unique=False)
    op.create_table('trip_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='tripsummarystatus'), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('diary_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_summaries_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_summaries')),
    sa.UniqueConstraint('trip_id', name=op.f('uq_trip_summaries_trip_id'))
    )
    op.create_table('itinerary_transits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('from_activity_id', sa.UUID(), nullable=True),
    sa.Column('to_activity_id', sa.UUID(), nullable=True),
    sa.Column('transport_mode', sa.String(length=30), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('route_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_activity_id'], ['itinerary_activities.id'], name=op.f('fk_itinerary_transits_from_activity_id_itinerary_activities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], name=op.f('fk_itinerary_transits_itinerary_day_id_itinerary_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_activity_id'], ['itinerary_activities.id'], name=op.f('fk_itinerary_transits_to_activity_id_itinerary_activities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_transits'))
    )
    op.create_index(op.f('ix_itinerary_transits_itinerary_day_id'), 'itinerary_transits', ['itinerary_day_id'], unique=False)
    op.create_table('next_trip_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_summary_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggested_places', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('started_agent_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_summary_id'], ['trip_summaries.id'], name=op.f('fk_next_trip_suggestions_trip_summary_id_trip_summaries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_trip_suggestions'))
    )
    op.create_index(op.f('ix_next_trip_suggestions_trip_summary_id'), 'next_trip_suggestions', ['trip_summary_id'], unique=False)
    op.create_table('review_moderation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=True),
    sa.Column('moderator_type', sa.Enum('SYSTEM', 'OPERATOR', 'ADMIN', name='moderatortype'), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'HIDE', 'RESTORE', name='moderationaction'), nullable=False),
    sa.Column('previous_status', sa.Enum('PRIVATE', 'PENDING', 'PUBLIC', 'REJECTED', 'HIDDEN', name='reviewstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PRIVATE', 'PENDING', 'PUBLIC', 'REJECTED', 'HIDDEN', name='reviewstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['place_reviews.id'], name=op.f('fk_review_moderation_logs_review_id_place_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_moderation_logs'))
    )
    op.create_index(op.f('ix_review_moderation_logs_review_id'), 'review_moderation_logs', ['review_id'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.Enum('SPAM', 'ABUSE', 'IRRELEVANT', 'FALSE_INFORMATION', 'OTHER', name='reviewreportreason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWING', 'RESOLVED', 'REJECTED', name='reviewreportstatus'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], name=op.f('fk_review_reports_reporter_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['place_reviews.id'], name=op.f('fk_review_reports_review_id_place_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_reports'))
    )
    op.create_index(op.f('ix_review_reports_review_id'), 'review_reports', ['review_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_version', sa.String(length=50), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='toolcallstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Lưu tối đa 7 ngày'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_tool_calls_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_summary_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('LODGING', 'TRANSPORT', 'FOOD', 'TICKET', 'SHOPPING', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['trip_summary_id'], ['trip_summaries.id'], name=op.f('fk_trip_expenses_trip_summary_id_trip_summaries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_expenses'))
    )
    op.create_index(op.f('ix_trip_expenses_trip_summary_id'), 'trip_expenses', ['trip_summary_id'], unique=False)
    op.create_table('trip_summary_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_summary_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('place_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('VISITED', 'SKIPPED', 'UNPLANNED', name='summaryplacestatus'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_user_corrected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_trip_summary_places_place_id_places'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_summary_id'], ['trip_summaries.id'], name=op.f('fk_trip_summary_places_trip_summary_id_trip_summaries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_summary_places'))
    )
    op.create_index(op.f('ix_trip_summary_places_trip_summary_id'), 'trip_summary_places', ['trip_summary_id'], unique=False)
    op.add_column('places', sa.Column('category_id', sa.Integer(), nullable=True, comment='FK → place_categories.id'))
    op.add_column('places', sa.Column('slug', sa.String(length=255), nullable=False, comment='Slug nhận diện duy nhất — URL safe'))
    op.add_column('places', sa.Column('description', sa.Text(), nullable=True, comment='Mô tả địa điểm'))
    op.add_column('places', sa.Column('address', sa.String(length=500), nullable=True, comment='Địa chỉ thực tế'))
    op.add_column('places', sa.Column('province', sa.String(length=100), nullable=True, comment='Tỉnh hoặc Thành phố'))
    op.add_column('places', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Giờ mở/đóng cửa theo ngày trong tuần (JSONB)'))
    op.add_column('places', sa.Column('min_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Giá vé tối thiểu — NUMERIC(15,2)'))
    op.add_column('places', sa.Column('max_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Giá vé tối đa — NUMERIC(15,2)'))
    op.add_column('places', sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False, comment='Đơn vị tiền tệ — ISO 4217'))
    op.add_column('places', sa.Column('average_rating', sa.Float(), nullable=True, comment='Điểm trung bình đánh giá'))
    op.add_column('places', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Danh sách ảnh (object_key, alt...) — JSONB'))
    op.add_column('places', sa.Column('visual_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Đặc điểm ảnh do Vision tool trích xuất (JSONB)'))
    op.add_column('places', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Địa điểm có đang hoạt động không'))
    op.add_column('places', sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID admin tạo địa điểm'))
    op.add_column('places', sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID admin cập nhật gần nhất'))
    op.add_column('places', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm tạo bản ghi (UTC, server clock)'))
    op.add_column('places', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm cập nhật gần nhất (UTC, server clock)'))
    op.alter_column('places', 'id',
               existing_type=sa.UUID(),
               comment='Primary key — UUID v4',
               existing_nullable=False)
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(),
               comment='Tên địa điểm',
               existing_nullable=False)
    op.alter_column('places', 'location',
               existing_type=Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True),
               comment='Tọa độ địa lý WGS84 — GiST index',
               existing_nullable=False)
    op.create_index(op.f('ix_places_category_id'), 'places', ['category_id'], unique=False)
    op.create_index('ix_places_is_active', 'places', ['is_active'], unique=False)
    op.create_geospatial_index('ix_places_location', 'places', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_places_province'), 'places', ['province'], unique=False)
    op.create_unique_constraint(op.f('uq_places_slug'), 'places', ['slug'])
    op.create_foreign_key(op.f('fk_places_category_id_place_categories'), 'places', 'place_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_places_category_id_place_categories'), 'places', type_='foreignkey')
    op.drop_constraint(op.f('uq_places_slug'), 'places', type_='unique')
    op.drop_index(op.f('ix_places_province'), table_name='places')
    op.drop_geospatial_index('ix_places_location', table_name='places', postgresql_using='gist', column_name='location')
    op.drop_index('ix_places_is_active', table_name='places')
    op.drop_index(op.f('ix_places_category_id'), table_name='places')
    op.alter_column('places', 'location',
               existing_type=Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True),
               comment=None,
               existing_comment='Tọa độ địa lý WGS84 — GiST index',
               existing_nullable=False)
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Tên địa điểm',
               existing_nullable=False)
    op.alter_column('places', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key — UUID v4',
               existing_nullable=False)
    op.drop_column('places', 'updated_at')
    op.drop_column('places', 'created_at')
    op.drop_column('places', 'updated_by')
    op.drop_column('places', 'created_by')
    op.drop_column('places', 'is_active')
    op.drop_column('places', 'visual_attributes')
    op.drop_column('places', 'images')
    op.drop_column('places', 'average_rating')
    op.drop_column('places', 'currency')
    op.drop_column('places', 'max_price')
    op.drop_column('places', 'min_price')
    op.drop_column('places', 'opening_hours')
    op.drop_column('places', 'province')
    op.drop_column('places', 'address')
    op.drop_column('places', 'description')
    op.drop_column('places', 'slug')
    op.drop_column('places', 'category_id')
    op.drop_index(op.f('ix_trip_summary_places_trip_summary_id'), table_name='trip_summary_places')
    op.drop_table('trip_summary_places')
    op.drop_index(op.f('ix_trip_expenses_trip_summary_id'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_review_reports_review_id'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_review_moderation_logs_review_id'), table_name='review_moderation_logs')
    op.drop_table('review_moderation_logs')
    op.drop_index(op.f('ix_next_trip_suggestions_trip_summary_id'), table_name='next_trip_suggestions')
    op.drop_table('next_trip_suggestions')
    op.drop_index(op.f('ix_itinerary_transits_itinerary_day_id'), table_name='itinerary_transits')
    op.drop_table('itinerary_transits')
    op.drop_table('trip_summaries')
    op.drop_index(op.f('ix_trip_alerts_trip_id'), table_name='trip_alerts')
    op.drop_table('trip_alerts')
    op.drop_index(op.f('ix_place_reviews_user_id'), table_name='place_reviews')
    op.drop_index('ix_place_reviews_place_status', table_name='place_reviews')
    op.drop_index(op.f('ix_place_reviews_place_id'), table_name='place_reviews')
    op.drop_table('place_reviews')
    op.drop_index(op.f('ix_itinerary_activities_place_id'), table_name='itinerary_activities')
    op.drop_index(op.f('ix_itinerary_activities_itinerary_day_id'), table_name='itinerary_activities')
    op.drop_table('itinerary_activities')
    op.drop_index('ix_gps_location_events_trip_recorded', table_name='gps_location_events')
    op.drop_index(op.f('ix_gps_location_events_trip_id'), table_name='gps_location_events')
    op.drop_geospatial_index('ix_gps_location_events_location', table_name='gps_location_events', postgresql_using='gist', column_name='location')
    op.drop_geospatial_index('idx_gps_location_events_location', table_name='gps_location_events', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('gps_location_events')
    op.drop_index(op.f('ix_agent_runs_workflow_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_workflow', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_session_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_trip_request_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_itinerary_proposals_itinerary_id'), table_name='itinerary_proposals')
    op.drop_table('itinerary_proposals')
    op.drop_index(op.f('ix_itinerary_days_itinerary_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index(op.f('ix_evaluation_results_itinerary_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_booking_offers_itinerary_id'), table_name='booking_offers')
    op.drop_table('booking_offers')
    op.drop_index(op.f('ix_trip_request_selected_places_trip_request_id'), table_name='trip_request_selected_places')
    op.drop_index(op.f('ix_trip_request_selected_places_place_id'), table_name='trip_request_selected_places')
    op.drop_table('trip_request_selected_places')
    op.drop_index(op.f('ix_media_files_user_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_message_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index('ix_itineraries_trip_request_status', table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_trip_request_id'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index('ix_trip_requests_user_status', table_name='trip_requests')
    op.drop_index(op.f('ix_trip_requests_user_id'), table_name='trip_requests')
    op.drop_index(op.f('ix_trip_requests_parent_trip_request_id'), table_name='trip_requests')
    op.drop_geospatial_index('ix_trip_requests_origin_location', table_name='trip_requests', postgresql_using='gist', column_name='origin_location')
    op.drop_index(op.f('ix_trip_requests_agent_session_id'), table_name='trip_requests')
    op.drop_geospatial_index('idx_trip_requests_origin_location', table_name='trip_requests', postgresql_using='gist', column_name='origin_location')
    op.drop_geospatial_table('trip_requests')
    op.drop_index(op.f('ix_place_narrations_place_id'), table_name='place_narrations')
    op.drop_table('place_narrations')
    op.drop_index(op.f('ix_operator_proposals_operator_id'), table_name='operator_proposals')
    op.drop_table('operator_proposals')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_index(op.f('ix_messages_agent_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_run_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_agent_memories_session_key', table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_agent_session_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_table('user_profile')
    op.drop_index('ix_agent_session_user_id_status', table_name='agent_session')
    op.drop_index(op.f('ix_agent_session_user_id'), table_name='agent_session')
    op.drop_table('agent_session')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_table('place_categories')
    op.drop_index('ix_information_sources_entity', table_name='information_sources')
    op.drop_table('information_sources')
    op.drop_index(op.f('ix_audit_access_logs_target_user_id'), table_name='audit_access_logs')
    op.drop_table('audit_access_logs')
    # ### end Alembic commands ###
